### PR TITLE
397: Fix name resolution bug

### LINKED ISSUE #397: Resolving a name conflict by committing a new yaml then refreshing the dashboard produces odd error message [2]
https://zapier.com/engine/hydrate/54157/.eJwVjF0OwiAQBu_yPfehKD_KIbwCWeliCRZN2aRpmt5dfJ2ZzIFcm1CNHPIEr-7aqovWA1Lm9xQqLQwPEqE4L1ylYUCcOZZQeIc3WhnXyadKl0H27z9_9KhstL4a_IFIaz_D3J7E9pqMZedoZM1xTNYSzvMHTAAqVw:1ckrpJ:Ptrz7kiuztDjb9ygLEf3dVw5xck/

Comments:

**Steps to reproduce:**

1. Add a repo with a snapcraft.yaml
2. Register a name other than the one in the yaml
3. Refresh the dasbhoard to show the "Names do not match" error
4. Go to GitHub and commit an updated yaml that matches the registered name
5. Refresh the dashboard

**What happens:**

* The error "The snapcraft.yaml uses the snap name “zeppelin-ev”, but you’ve registered the name “zeppelin-ev”" is shown.

**What should happen:**

* The accordion collapses and no error is shown.

---
Creator: Robin Winslow
Assignees: 
Copied from Trello card: https://trello.com/c/4uWTYl3G/341-resolving-a-name-conflict-by-committing-a-new-yaml-then-refreshing-the-dashboard-produces-odd-error-message
Labels: Bug,copy to github

### PR DESCRIPTION
**Pull request by katiefenn**
- Added feature to close name mismatch dropdown if name updates and is
  fixed
- Fixes #397

### CODE REVIEW

File: src/common/components/repository-row/index.js [hunk 1]
```diff
@@ -154,6 +154,17 @@ class RepositoryRow extends Component {
...
       }, 2000);
     }
+
+    // Close snap name mismatch dropdown if
+    // name is updated and fixed
+    const oldSnapProp = this.props.snap;
+    const newSnapProp = nextProps.snap;
+    if (snapNameIsMismatched(oldSnapProp) && !snapNameIsMismatched(newSnapProp)) {
+      this.setState({
+        ...this.state,
```
Comment (bartaz) [inline src/common/components/repository-row/index.js]: This is not needed. `setState` will do the magic, you just need to set what you want to change.
