### PR TITLE
Fixes for build status not updating correctly on my repos page

### LINKED ISSUE #716: "Never built" text never updates
The never built state doesn't automatically change to building.

screen shot 2017-05-04 at 13 39 42
screen shot 2017-05-04 at 13 44 47

### PR DESCRIPTION
**Pull request by bartaz**
Fixes #716

### CODE REVIEW

File: src/common/components/build-row/index.js [hunk 1]
```diff
@@ -66,7 +66,7 @@ BuildRow.propTypes = {
   buildId:  PropTypes.string,
   buildLogUrl: PropTypes.string,
   architecture: PropTypes.string,
-  colour:  PropTypes.oneOf(['green', 'yellow', 'red', 'grey']),
+  colour:  PropTypes.oneOf(['green', 'yellow', 'blue', 'red', 'grey']),
```
Comment (bartaz) [inline src/common/components/build-row/index.js]: Blue was missing from props validation.

File: src/common/components/build-status/buildStatus.css [hunk 2]
```diff
@@ -3,6 +3,11 @@
   color: $success;
 }
 
+.buildStatus.blue,
+.buildStatus.blue a {
+  color: $information;
```
Comment (bartaz) [inline src/common/components/build-status/buildStatus.css]: ... and from CSS.

File: src/common/helpers/snap-builds.js [hunk 3]
```diff
@@ -136,7 +138,7 @@ const LaunchpadStoreUploadStates = {
 function mapBuildAndUploadStates(buildState, uploadState) {
   switch (buildState) {
     case LaunchpadBuildStates.NEEDSBUILT:
-      return UserFacingState.NEVER_BUILT;
+      return UserFacingState.BUILDING_SOON;
```
Comment (bartaz) [inline src/common/helpers/snap-builds.js]: When there is build object on LP it means that it will be building soon for BSI UI.

File: src/common/components/repositories-home/index.js [hunk 4]
```diff
@@ -59,11 +49,16 @@ class RepositoriesHome extends Component {
   }
 
   componentWillReceiveProps(nextProps) {
-    const snapsLength = nextProps.snaps.ids.length;
-
-    if ((this.props.snaps.success !== nextProps.snaps.success)
```
Comment (bartaz) [inline src/common/components/repositories-home/index.js]: Main source of the bug.

We were relying on `success` being changed, but after refactoring it stayed `true` after first success even during subsequent fetches.

File: src/common/components/repositories-home/index.js [hunk 5]
```diff
@@ -59,11 +49,16 @@ class RepositoriesHome extends Component {
...
-        || (snapsLength === 0)) {
-      this.fetchData(nextProps);
+    const { hasSnaps, snaps } = nextProps;
+    // if snaps stopped fetching
+    if ((this.props.snaps.isFetching !== snaps.isFetching) && !snaps.isFetching) {
```
Comment (bartaz) [inline src/common/components/repositories-home/index.js]: Rewritten the condition not to rely on `success` flag anymore, and always reload builds when snaps stopped fetching.

File: src/common/components/build-row/index.js (hunk 1 above)
Comment (earnubs) [inline src/common/components/build-row/index.js]: What about using the exported values where they're defined? https://github.com/canonical-ols/build.snapcraft.io/blob/master/src/common/components/build-status/index.js#L43

File: src/common/components/build-status/buildStatus.css (hunk 2 above)
Comment (earnubs) [inline src/common/components/build-status/buildStatus.css]: Oops.

File: src/common/components/repositories-home/index.js (hunk 4 above)
Comment (earnubs) [inline src/common/components/repositories-home/index.js]: This seems like another reason not to like success as a feature of state per se?

Comment (bartaz) [inline src/common/components/repositories-home/index.js]: Yup, especially that we don't handle it consistently - sometimes `success` is cleared with every new fetch, sometimes not...
