### PR TITLE
Fixes for passing repository to build details page

### LINKED ISSUE #373: Navigating to another build page fails to show details
Steps to reproduce:

- Reload the dashboard
- Click on any latest build
- Click on the dashboard
- Click on any other latest build

What happens:

- The build details are not shown
- The build log is shown
- The install instructions are shown

What should happen:

- The build details are shown
- The build log is shown

### PR DESCRIPTION
**Pull request by bartaz**
Fixes #373

The issue was caused by `withRepository` container that was passing repository data from the store to build details page even if the repository in the store was different from the one in the URL.

With this PR we make sure to properly set repository in the store when it doesn't match the one in the URL. Also if these repos don't match child component is not rendered (until value in the store is properly propagated).

### CODE REVIEW

File: test/unit/src/common/containers/t_with-repository.js [hunk 1]
```diff
@@ -0,0 +1,110 @@
...
+
+    const DummyWithRepo = withRepository(Dummy);
+
+    // shallow render container component
+    const dummyWithRepo = shallow(<DummyWithRepo store={store} params={params}/>);
+
+    // get child components/instances from rendered component
+    wrapper = dummyWithRepo.first();
+    instance = wrapper.shallow().instance();
+    wrapped = wrapper.dive();
```
Comment (bartaz) [inline test/unit/src/common/containers/t_with-repository.js]: Higher order components make components nested, so to properly test them with shallow rendering we need to dive into the children.

File: src/common/containers/with-repository.js [hunk 2]
```diff
@@ -22,7 +23,11 @@ function withRepository(WrappedComponent) {
     render() {
       const { fullName, ...passThroughProps } = this.props; // eslint-disable-line no-unused-vars
 
-      return (this.props.repository
+      // only render if current repo in the store matches repo in URL params
+      const { repository } = this.props;
+      const isReady = repository && repository.fullName === fullName;
+
+      return (isReady
```
Comment (katiefenn) [inline src/common/containers/with-repository.js]: Won't this hide the `WrappedComponent` on occasions that the repository is being fetched? What if a child component one day wants to show a spinner while repo data is being loaded?

File: test/unit/src/common/containers/t_with-repository.js [hunk 3]
```diff
@@ -0,0 +1,110 @@
...
+    fullName: 'anowner/aname'
+  };
+
+  let store;
+
+  let wrapper;  // WithRepository rendered wrapper
+  let instance; // WithRepository wrapper instance
+  let wrapped;  // wrapped Dummy component
+
+  const setupDummy = (repository = REPO, params = PARAMS) => {
```
Comment (katiefenn) [inline test/unit/src/common/containers/t_with-repository.js]: Extracting helper functions to the bottom of the file might make the body of the unit test files a bit easier to read.

File: src/common/containers/with-repository.js (hunk 2 above)
Comment (bartaz) [inline src/common/containers/with-repository.js]: This data is not being fetched. It's built from URL params and set to the store.

So the owner/name pair from the URL is turned in the reducer into full repository object (with owner, name, fullName, url). 

This way WrappedComponent can rely on full repository object being available (and not parse it from URL itself).

File: test/unit/src/common/containers/t_with-repository.js (hunk 3 above)
Comment (katiefenn) [inline test/unit/src/common/containers/t_with-repository.js]: Can this helper function be reworked to return `wrapper` instead of writing it to a global? It would make it possible to move the function to the bottom of the file, making the body of the unit test easier to read.

File: src/common/containers/with-repository.js (hunk 2 above)
Comment (katiefenn) [inline src/common/containers/with-repository.js]: Cool, that makes sense now 👍

File: test/unit/src/common/containers/t_with-repository.js (hunk 3 above)
Comment (bartaz) [inline test/unit/src/common/containers/t_with-repository.js]: Possibly it could, but what it actually prepares is `wrapper`, `instance` and `wrapped` objects that are used in tests.

If it only returns `wrapper`, each time we call setupDummy we would need to recreate those manually.

If that would help this helper function can be moved to the end of `describe`, so it will be kept in the scope of the variables it uses, but will not take space at the top of tests file.

Comment (katiefenn) [inline test/unit/src/common/containers/t_with-repository.js]: I think the extra lines to manually set `instance` and `wrapped` would be worth it, but moving it to the bottom of the closure would also work.
