### PR TITLE
Show non-admin repos as disabled on the list

### LINKED ISSUE #787: Repository paging in select-repositories is broken
Paged views are sliced incorrectly...

### PR DESCRIPTION
**Pull request by bartaz**
Fixes #787 
screen shot 2017-05-18 at 13 18 53

### CODE REVIEW

File: src/common/components/select-repository-row/index.js [hunk 1]
```diff
@@ -16,32 +16,32 @@ class SelectRepositoryRow extends Component {
     // TODO tidy up when we get rid of prefixes
     const isChecked = repository.isSelected || isEnabled;
     const isFetching = repository.isFetching;
-    const isDisabled = isEnabled || isFetching;
+    const isDisabled = isEnabled || isFetching || !repository.isAdmin;
```
Comment (cjwatson) [inline src/common/components/select-repository-row/index.js]: This is pre-existing, I know, but it might be nice to sort out slightly different names for either or both of `isEnabled` (is repository already enabled as a snap build) and `isDisabled` (should this repository row be unavailable for selection) so that it's less terribly confusing.
