### PR TITLE
Fixes #355 - reusing existing help box to show build debug instructions

### LINKED ISSUE #355: [Build detail] Providing instructions for debugging failed build [1]
---

Copied from Trello card: https://trello.com/c/pGN2BJQq/232-build-detail-consider-providing-instructions-for-debugging-failed-build
Labels:

### PR DESCRIPTION
**Pull request by bartaz**
screen shot 2017-03-16 at 15 49 48

### CODE REVIEW

File: src/common/containers/build-details.js [hunk 1]
```diff
@@ -22,6 +22,27 @@ class BuildDetails extends Component {
     const { repository, buildId, build } = this.props;
     const { snap, error, isFetching } = this.props.snapBuilds;
 
+    const buildFailed = (build.statusMessage === 'Failed to build');
```
Comment (bartaz) [inline src/common/containers/build-details.js]: Currently the only 'status' we have for build is a message from LP, so we need to do a string comparison to detect particular status.

File: src/common/components/help/install-snap/index.js [hunk 2]
```diff
@@ -9,13 +9,14 @@ export default class HelpInstallSnap extends Component {
   render() {
     const { headline, name, revision } = this.props;
     const revOption = revision ? `--revision=${ revision }` : '';
+    const command = this.props.children || `sudo snap install --edge ${name} ${revOption}`;
```
Comment (earnubs) [inline src/common/components/help/install-snap/index.js]: maybe destructure children at line 10?

Comment (bartaz) [inline src/common/components/help/install-snap/index.js]: Good point, fixed.
